version: '3.8'
services:
  user_backend:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on: 
      - db_user

  user_queue:
    build: .
    command: 'python consumer.py'
    depends_on:
      - db_user  
  
  db_user:
    image: mysql:5.7.22
    restart: always
    environment: 
      MYSQL_DATABASE: user
      MYSQL_USER: root
      MY_SQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - .dbdata:/var/lib/mysql
    ports: 
      - 33067:3306